services:
  pgvector:
    container_name: pgdb-store
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=dbCryptoCurrency'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=admin'
    volumes:
      - chatbot_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - chatbot-net
  chatbot-back:
    build: ./backend
    container_name: chatbot-back
    environment:
      - DB_URL=jbdc:postgresql://pgdb-store:5432/dbCryptoCurrency
    ports:
      - "8074:8074"
    networks:
      - chatbot-net
    depends_on:
      - pgvector
  chatbot-fornt:
    build: ./frontend
    container_name: chatbot-front
    ports:
      - "8086:80"
    networks:
      - chatbot-net
    depends_on:
      - chatbot-back
volumes:
  chatbot_data:
networks:
  chatbot-net:
    driver: bridge